feat(firstHooK): Написал хук и выложил на npm
Kalabass/Web-bee-npm-modules pull request #1
Opened 2024-07-04 15:45 UTC by Kalabass

2024-07-05 05:12 UTC, al-revenko requested changes

2024-07-05 05:12 UTC, al-revenko commented on use-document-visibility/src/useDocumentVisibility.ts
> +	);
Забавно, но я тоже попался в эту ловушку когда делал свой хук)

Кароч, вместо того чтобы городить свой велосипед реализаций подписок, используй реализацию из DOM.
Вот пример как я переписал свой:

```js
  const onVisibilityChange = (fn: CallbackType) => {
    const callback = () => fn(getVisisbleStatus()); //  fn(!document.hidden)

    document.addEventListener('visibilitychange', callback);

    return () => document.removeEventListener('visibilitychange', callback);
  };
```

2024-07-05 05:12 UTC, al-revenko commented on use-document-visibility/src/useDocumentVisibility.ts
> +	}, [subscribers]);
Зачем используешь useCallback? По моему нет смысла кэшировать хандлер, т.к его инициализация не очень трудозатратная

2024-07-05 08:48 UTC, aidagalimova approved these changes

2024-07-05 12:43 UTC, Kalabass commented on use-document-visibility/src/useDocumentVisibility.ts
> +	}, [subscribers]);
Согласен, лишнего накинул, убрал все, что можно было убрать)

2024-07-05 16:39 UTC, al-revenko approved these changes

2024-07-05 23:26 UTC, sspopkov commented on npmModulesTest/src/components/DocumentVisibility.tsx
> +	useEffect(() => {
Добавь отписку от обработчика при размонтировании компонента и очистку таймера

2024-07-05 23:26 UTC, sspopkov commented on npmModulesTest/src/hooks/useDocumentVisibility.ts
> +	useEffect(() => {
useEffect обычно пишем в конце компонента, после других функций

2024-07-05 23:26 UTC, sspopkov commented on use-document-visibility/src/useDocumentVisibility.ts
> +	const [subscribers, setSubscribers] = useState<VisibilityChangeHandler[]>([]);
Список подписчиков не влияет напрямую на то, что отображается или возвращается из хука. Поэтому здесь лучше использовать useRef, а не useState, чтобы не ререндерить компонент при каждом изменении подписчика

2024-07-05 23:32 UTC, G00syara commented
Претир сдох, пофкси пожалуйста, оступы в 4 таба это супер много, достаточно одного

2024-07-07 12:25 UTC, sspopkov approved these changes

2024-07-07 12:25 UTC, merged