Features/second hook
Kalabass/Web-bee-npm-modules pull request #2
Opened 2024-07-09 12:02 UTC by Kalabass

2024-07-09 12:22 UTC, aidagalimova commented on npmModulesTest/src/hooks/UseMediaQuery.ts
> +      mqlArr.forEach((mql) => mql.addEventListener("change", handleMatch));
можно не создавать для каждого аргемента отдельный слушатель, а объединить все в один запрос через and Например `window.matchMedia((min-width: 1px) and (max-resolution: 2))`

2024-07-09 12:25 UTC, aidagalimova commented on npmModulesTest/src/components/MediaQuery.tsx
> +  minResolution?: string | number;
не указано что строка должна быть определенного вида  `{число}dppx`

2024-07-09 13:19 UTC, Kalabass commented on npmModulesTest/src/hooks/UseMediaQuery.ts
> +      mqlArr.forEach((mql) => mql.addEventListener("change", handleMatch));
исправил

2024-07-09 13:19 UTC, Kalabass commented on npmModulesTest/src/components/MediaQuery.tsx
> +  minResolution?: string | number;
исправил

2024-07-09 13:20 UTC, aidagalimova approved these changes

2024-07-10 10:17 UTC, al-revenko requested changes
В проекте структура перемешана. Хук из первого задания живёт в отдельной папке, а хук и компонент из второго задания лежат в npmModulesTest. Вынеси всю логику второго задания в отдельную папку со своим package.json

2024-07-10 10:17 UTC, al-revenko commented on npmModulesTest/src/components/react-responsive/MediaQuery.tsx
> +  maxResolution?: `${number}dppx` | number;
Вынеси `'${number}dppx' | number` в отдельный тип

2024-07-10 13:25 UTC, Kalabass commented on npmModulesTest/src/components/react-responsive/MediaQuery.tsx
> +  maxResolution?: `${number}dppx` | number;
добавил тип и поменял структуру

2024-07-10 15:47 UTC, al-revenko requested changes

2024-07-10 15:47 UTC, al-revenko commented on README.md
После установки зависимостей и запуска npm run dev, в корне проекта, появляется ошибка:

`Failed to resolve entry for package "@kalabass/react-responsive". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]`

![Снимок](https://github.com/Kalabass/Web-bee-npm-modules/assets/73707133/166b6524-942f-4712-b8aa-a2c8e7a33336)

2024-07-10 15:47 UTC, al-revenko commented on README.md
Короче это потому что пакет @kalabass/react-responsive не был скомпилирован, у меня не было dist и он поэтому крашнулся. Добавь в README пометку о том что надо сначала запустить билд.

Или в идеале вообще сделать так, чтобы при запуске npm run dev, из корня, одновременно запускался ещё и npm run start (rollup -c -w) пакета @kalabass/react-responsive . Например эт можно сделать с помощью npm workspaces и пакета concurrently. Но это так, по желанию

2024-07-10 16:46 UTC, Kalabass commented on README.md
Добавил сборку пакета перед запуском

2024-07-10 17:34 UTC, kseniakap approved these changes

2024-07-10 17:34 UTC, kseniakap commented on react-responsive/src/MediaQuery/index.tsx
> +  if (typeof children === "function") {
Можно сократить запись, вместо If else использовать тернарник
``` return typeof children === "function" ? children(isMatching) : isMatching ? children : null;```

2024-07-11 05:28 UTC, al-revenko approved these changes

2024-07-14 09:44 UTC, sspopkov approved these changes

2024-07-14 09:44 UTC, merged